### ISSUE TITLE
Connection to z/OSMF throws error if z/OSMF is configured to use TLSv1.2

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/explorer-api-common#56]
By default, z/OSMF is configured with this value `IZU_SSL_PROTOCOL=SSL_TLSv2`.

Based on description https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/protocols.html, it seems support `https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/protocols.html`.

But if the user want to disable the usage of deprecated protocols like TLSv1, etc, and configure the z/OSMF with this option: `IZU_SSL_PROTOCOL=TLSv1.2`, the api-common will throw an error:

```
<ZWEEAD1:https-jsse-nio-8547-exec-6:65796> ZWESVUSR ERROR (o.z.a.c.s.CustomAuthenticationProvider,CustomAuthenticationProvider.java:54)
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
.at com.ibm.jsse2.av.a(av.java:841)
.at com.ibm.jsse2.av.i(av.java:136)
.at com.ibm.jsse2.av.a(av.java:1001)
.at com.ibm.jsse2.av.startHandshake(av.java:991)
.at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
.at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
....
Caused by: java.io.EOFException: SSL peer shut down incorrectly (edited)
```

I believe this is caused by line: https://github.com/zowe/explorer-api-common/blob/master/explorer-api-common/src/main/java/org/zowe/api/common/connectors/zosmf/ZosmfConnector.java#L77.

```
SSLContext sslcontext = SSLContext.getInstance("TLS");
```

To reproduce, configure z/OSMF with `IZU_SSL_PROTOCOL=TLSv1.2` and restart Zowe.

@NayerNajafi

**Comment by jackjia-ibm** [comment]
This is a potential solution: https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/matchsslcontext_tls.html#matchsslcontext_tls

**Comment by jackjia-ibm** [comment]
Option `-Dcom.ibm.jsse2.overrideDefaultTLS=true` confirmed works ok with z/OSMF configured in both ways.

jobs api already added this option with https://github.com/zowe/jobs/pull/88/files.
data-sets api already added this option with https://github.com/zowe/data-sets/pull/145/files
