### ISSUE TITLE
Add more validation/error handling to the connection to z/OSMF

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/explorer-api-common#9]
Particularly provide a better error message if the connection to z/OS fails, or we don't get an LTPA key back.
java.lang.NullPointerException: null
       at org.zowe.api.common.security.CustomAuthenticationProvider.authenticate(CustomAuthenticationProvider.java:48) ~[explorer-api-common-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
       at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) [spring-security-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
       at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199) [spring-security-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
       at

**Comment by stevenhorsman** [comment]
I have some added tests and logging, but waiting for a pending fix to preemptive authentication before this goes in.
